### ISSUE TITLE
Rover loading issue

### ISSUE THREAD

**Issue by jarosm** [jarosm/KSP-BonVoyage#1]
Submited to the old repo by @snakedog49

Whenever I load in my rover from doing a drive. If it is halfway through the ground. It explodes. If it is fully clipped through the ground then it falls to sea level and explodes. But if the whole rover is above ground it just falls down. And while I know explosions are cool and all its killing my crew members and a lot of money is being invested in rescue missions that end up exploding because of this. It makes me afraid to open my rovers after sending them to a destination. This has been happening in the most recent version of the game. Please fix!

**Comment by VoidDot** [comment]
i had the same thing happen to me i was going to pilot my rover then is was in the ground and shot in the air completely destroying it

**Comment by jarosm** [comment]
Fixed in version 0.14.0 ... I hope :)

**Comment by theonegalen** [comment]
Also, use World Stabilizer, as this sounds like a similar problem to the stock jump-on-load bug.

**Comment by jarosm** [comment]
> 
> 
> Also, use World Stabilizer, as this sounds like a similar problem to the stock jump-on-load bug.

No, it isn't similar problem. World stabilizer accidentaly fixes it also, but is not needed anymore.
