### ISSUE TITLE
Rover resumes 90 degrees rotated

### ISSUE THREAD

**Issue by szundi** [jarosm/KSP-BonVoyage#12]
[KSP.log](https://github.com/jarosm/KSP-BonVoyage/files/4023333/KSP.log)

Hello, I am using a rover design that uses the white rover body rotated, and on top of that I placed a kerbal seat. After landing, I tell that from now on the kerbal seat is controlling the rover, so the navball gets correct. Without this the navball would tell me I am seeing the sky.

When bonvoyage returns to my rover, it restores it seeing the sky. Coincidence? I am supspecting that you are using the direction of some kind of default control part, but the adequate startegy would be to look up the one that had the control when the mission was unloaded to maintain proper direction. Or to read the direction some other way that is universal.

Bon voyage has flipped/destroyed 2 of my rovers and I am playing in "ironman mode". This makes me sad. 😄 

Keep up your good work! 👍 Thank you!

**Comment by jarosm** [comment]
https://github.com/jarosm/KSP-BonVoyage/wiki/Settings

**Rotation vector advanced tweakable** ;)

The default source of rotation of a vessel is the root part, so it's used in this case. Change in rotation vector for given rover fix the flipping of rovers with rotated root part (Rovemate for example).

**Comment by jarosm** [comment]
See above
