### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by jarosm** [jarosm/KSP-BonVoyage#25]
Done by @Raven-233486

https://drive.google.com/file/d/11T_AvN3InqOFEkXR9c3zs4XbiuziXgYp/view?usp=sharing

**Comment by jarosm** [comment]
@Raven-233486 Can you translate these three lines too?

#LOC_BV_Warning_Landed_Splashed = Kerbal must be landed or in the water
#LOC_BV_Title_KerbalArrived = Kerbal arrived
#LOC_BV_Warning_CantUseBatteries = Batteries can't be used.

You can add them to your cfg. Updated source file is here and will be in the next version: https://github.com/jarosm/KSP-BonVoyage/blob/master/GameData/BonVoyage/Localization/en-us.cfg

**Comment by ToumanLin** [comment]
> @Raven-233486 Can you translate these three lines too?
> 
> #LOC_BV_Warning_Landed_Splashed = Kerbal must be landed or in the water
> #LOC_BV_Title_KerbalArrived = Kerbal arrived
> #LOC_BV_Warning_CantUseBatteries = Batteries can't be used.
> 
> You can add them to your cfg. Updated source file is here and will be in the next version: https://github.com/jarosm/KSP-BonVoyage/blob/master/GameData/BonVoyage/Localization/en-us.cfg

What does "kerbal" mean ? Is it a ship? Or a rover ?

**Comment by jarosm** [comment]
@raven-233486
> What does "kerbal" mean ? Is it a ship? Or a rover ?

In this case it is that little green humanoid creature. There will be a new module, which can move Kerbals too.

**Comment by ToumanLin** [comment]
Okay. Orignal english is enough, and they will sense the meaning.

**Comment by jarosm** [comment]
Added to version 1.3.0

**Comment by ToumanLin** [comment]
A, I forgot it.....
#LOC_BV_Warning_Landed_Splashed = Kerbal must be landed or in the water
载具必须着陆或入水
#LOC_BV_Title_KerbalArrived = Kerbal arrived 载具已到达
#LOC_BV_Warning_CantUseBatteries = Batteries can't be used. 无法使用电池

Martin Jaros <notifications@github.com> 于2021年2月7日周日 下午11:00写道：

**Comment by jarosm** [comment]
@Raven-233486 Ok, I add it to the next version, that will be out soon (I hope). If not, then I release only a language fix.

**Comment by jarosm** [comment]
@Raven-233486 Hi, can you check, if this translation is ok?

#LOC_BV_HeightOffset = Height offset
#LOC_BV_HeightOffset = 高度偏移

**Comment by ToumanLin** [comment]
It's right

**Comment by ToumanLin** [comment]
Because I'm a student, I don't always have time to check my email...
I won't be so late next time, I mean, I'msorry.
