### ISSUE TITLE
Wrong detection of usable converters when fuel cell contains more modules of type ModuleResourceConverter

### ISSUE THREAD

**Issue by jarosm** [jarosm/KSP-BonVoyage#30]
_(Wrong first assumption of bug origin - Internal LFO of Malemute rover is not detected when using fuel cells.)_

When fuel cell contains more then one ModuleResourceConverter module, then every module is processed. In reality, only one module can be active.

**Comment by jarosm** [comment]
![](https://imgur.com/gGwfkfP.png)

**Comment by Tacombel** [comment]
Perhaps is something different
![image](https://user-images.githubusercontent.com/17971083/108978899-6232e880-768a-11eb-9ac4-feb24792eb07.png)

**Comment by jarosm** [comment]
@Tacombel Is it working with other rovers?

**Comment by Tacombel** [comment]
I am testing it. Next I will try a stock rover and see.

**Comment by Tacombel** [comment]
This one also doesn't work, so I probably have a mod conflict somewhere
![image](https://user-images.githubusercontent.com/17971083/108980976-914a5980-768c-11eb-841e-d3e835732180.png)

**Comment by jarosm** [comment]
@Tacombel I'm leaving this issue open so feel free to update it here

**Comment by Tacombel** [comment]
No problem using monopropellant
![image](https://user-images.githubusercontent.com/17971083/108981948-8f34ca80-768d-11eb-827a-cb384658cb4b.png)

**Comment by jarosm** [comment]
@Tacombel Maybe the problem is, that there are two fuel options (LFO and LH2O)? BV probably can't sort it out properly. If it is the case, then it definitely needs some improvement.

**Comment by Tacombel** [comment]
Probably. Malemute with monoprop is detected correctly. And this FC only have one option
![image](https://user-images.githubusercontent.com/17971083/108985449-5a2a7700-7691-11eb-9a78-01b39820b960.png)

**Comment by jarosm** [comment]
@Tacombel I need to know from which mod that fuell cell is or which mod adds that second option.

**Comment by Tacombel** [comment]
The fuel cell is squad. The mod is Cryotanks.
![image](https://user-images.githubusercontent.com/17971083/108986796-d1acd600-7692-11eb-8e4e-51bf83d48992.png)

patch CryoTanksFuelCells.cfg

//Adds a converter to fuel cells to produce ElectricCharge from LqdHydrogen and Oxidizer

//Produces ElectricCharge and consumes Oxidizer at the same rate as stock LFO converter
//Uses the same 15:1 unit ratio of LqdHydrogen to Oxidizer as CryoTanks, etc.

//N.B.: LH2/O->EC requires only 2/3 as much reaction mass per EC as LF/O->EC, but...
//...powering ZBO tanks with LH2O fuel cells uses 11.88x more LH2 than allowing boil-off

@PART[FuelCell]:FOR[CryoTanks]
{
  @MODULE[ModuleResourceConverter]:HAS[#ConverterName[Fuel?Cell]]
  {
    @ConverterName = Fuel Cell (LFO)
    @StartActionName = Start Fuel Cell (LFO)
    @StopActionName = Stop Fuel Cell (LFO)
    @ToggleActionName = Toggle Fuel Cell (LFO)
  }
  MODULE
  {
    name = ModuleResourceConverter
    ConverterName = Fuel Cell (LH2O)
    StartActionName = Start Fuel Cell (LH2O)
    StopActionName = Stop Fuel Cell (LH2O)
    ToggleActionName = Toggle Fuel Cell (LH2O)
    FillAmount = 0.95
    AutoShutdown = false
    GeneratesHeat = false
    UseSpecialistBonus = false
    INPUT_RESOURCE
    {
      ResourceName = LqdHydrogen
      Ratio = 0.0309375
      FlowMode = STAGE_PRIORITY_FLOW
    }
    INPUT_RESOURCE
    {
      ResourceName = Oxidizer
      Ratio = 0.0020625
      FlowMode = STAGE_PRIORITY_FLOW
    }
    OUTPUT_RESOURCE
    {
      ResourceName = ElectricCharge
      Ratio = 1.5
      DumpExcess = false
    }
  }
}

@PART[FuelCellArray]:FOR[CryoTanks]
{
  @MODULE[ModuleResourceConverter]:HAS[#ConverterName[Fuel?Cell]]
  {
    @ConverterName = Fuel Cell (LFO)
    @StartActionName = Start Fuel Cell (LFO)
    @StopActionName = Stop Fuel Cell (LFO)
    @ToggleActionName = Toggle Fuel Cell (LFO)
  }
  MODULE
  {
    name = ModuleResourceConverter
    ConverterName = Fuel Cell (LH2O)
    StartActionName = Start Fuel Cell (LH2O)
    StopActionName = Stop Fuel Cell (LH2O)
    ToggleActionName = Toggle Fuel Cell (LH2O)
    FillAmount = 0.95
    AutoShutdown = false
    GeneratesHeat = false
    UseSpecialistBonus = false
    INPUT_RESOURCE
    {
      ResourceName = LqdHydrogen
      Ratio = 0.37125
      FlowMode = STAGE_PRIORITY_FLOW
    }
    INPUT_RESOURCE
    {
      ResourceName = Oxidizer
      Ratio = 0.02475
      FlowMode = STAGE_PRIORITY_FLOW
    }
    OUTPUT_RESOURCE
    {
      ResourceName = ElectricCharge
      Ratio = 18
      DumpExcess = false
    }
  }
}

//LH2O fuel cells produce Water as an byproduct at a rate of 9/8 * Oxidizer by mass
//Only if mods that use Water are present

@PART[FuelCell]:AFTER[CryoTanks]:NEEDS[KolonyTools|TacLifeSupport|KerbalHealth]
{
  @MODULE[ModuleResourceConverter]:HAS[#ConverterName[Fuel?Cell??LH2O?]]
  {
    OUTPUT_RESOURCE
    {
      ResourceName = Water
      Ratio = 0.0116016
      DumpExcess = true
    }
  }
}

@PART[FuelCellArray]:AFTER[CryoTanks]:NEEDS[KolonyTools|TacLifeSupport|KerbalHealth]
{
  @MODULE[ModuleResourceConverter]:HAS[#ConverterName[Fuel?Cell??LH2O?]]
  {
    OUTPUT_RESOURCE
    {
      ResourceName = Water
      Ratio = 0.13922
      DumpExcess = true
    }
  }
}

**Comment by jarosm** [comment]
@Tacombel Found it. The problem is, that BV finds both resource converters and is expecting fuel for both of them. I bet, that generated power for that fuel cell is shown in the BV control panel as sum of output values of LFO and LH2O converters.

**Comment by Tacombel** [comment]
@jarosm And of course you are right. This is 2x1.5 Ec/s fuel cells
![image](https://user-images.githubusercontent.com/17971083/109022949-9f17d300-76bc-11eb-80eb-5cd2b117ccaf.png)

**Comment by jarosm** [comment]
Fixed in version 1.3.1
