### ISSUE TITLE
Russian localization update

### ISSUE THREAD

**Issue by jarosm** [jarosm/KSP-BonVoyage#34]
@kovakthemost Hi, can you check if this translation is ok?

#LOC_BV_HeightOffset = Height offset
#LOC_BV_HeightOffset = Смещение по высоте

**Comment by kovakthemost** [comment]
> @kovakthemost Hi, can you check if this translation is ok?
> 
> #LOC_BV_HeightOffset = Height offset
> #LOC_BV_HeightOffset = Смещение по высоте

Yes, I think it's all right.

**Comment by jarosm** [comment]
@kovakthemost thanks
