### ISSUE TITLE
CKAN - wrong source code URL

### ISSUE THREAD

**Issue by MaximeBrean** [jarosm/KSP-BonVoyage#4]
I don't know if you handle CKAN update for this mod yourself or if someone else do this (there is no statement on the forum post about it). If someone else manage CKAN update, apologize for disturbing you whit that and just close the ticket.
If you manage it: the source code URL link to RealGecko's repository on GitHub instead of this one.

**Comment by jarosm** [comment]
I don't manage CKAN, but I see this in NetKAN source:

{
    "$kref": "#/ckan/spacedock/950",
    "identifier": "BonVoyage",
    "spec_version": "v1.4",
    "license": "GPL-3.0",
    "x_via": "Automated SpaceDock CKAN submission"
}

As I understand it, it's an automated process by SpaceDock and the SpaceDock BonVoyage page is the right one.

**Comment by jarosm** [comment]
And I think that I know what you mean. There realy was a link to the RealGecko's github on SpaceDock, but I changed it yesterday to my repo.

**Comment by MaximeBrean** [comment]
Ok, nevermind this, it's ok now.
I don't know why CKAN showed the wrong URL today ... Cache issue maybe ?
