### ISSUE TITLE
NFE + System Heat unsupported (includes fix)

### ISSUE THREAD

**Issue by johnabsher** [jarosm/KSP-BonVoyage#41]
To fully support the latest versions of NFE, you'll need to also support `ModuleSystemHeatFissionReactor`.
I think [this line here](https://github.com/jarosm/KSP-BonVoyage/blob/master/BonVoyage/BVController.cs#L425) is the one you'll need to update.

_Originally posted by @johnabsher in https://github.com/jarosm/KSP-BonVoyage/issues/37#issuecomment-877693132_

**Comment by enkido** [comment]
Got the same problem...

**Comment by jarosm** [comment]
Supported in version 1.4.1
